config/routes.rb
Rails.application.routes.draw do
  
  resources :armies
  resources :fights
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'home#index'

  get 'home' => 'home#index'
  get 'simulator' => 'home#armyfight'
  get 'tutorial' => 'home#tutorial'
  get 'events' => 'home#events'
  post 'destroy_armies' => 'fights#destroy_armies'
  get 'all_fights' => 'fights#all_fights'
  get "play/:id" => 'fights#play'
  post 'watched_fight' => 'fights#watched_fight'

end

app/models/army.rb
class Army < ActiveRecord::Base
	belongs_to :fight
	has_many :targets, :dependent => :destroy

	def create_army(params)
		self.unit_name = params[:army][:unit]
		self.hp_from = params[:army][:stats][:hp_from]
		self.hp_to = params[:army][:stats][:hp_to]
		self.dmg_from = params[:army][:stats][:dmg_from]
		self.dmg_to = params[:army][:stats][:dmg_to]
		self.def_inf_from = params[:army][:stats][:def_inf_from]
		self.def_inf_to = params[:army][:stats][:def_inf_to]
		self.def_hors_from = params[:army][:stats][:def_hors_from]
		self.def_hors_to = params[:army][:stats][:def_hors_to]
		self.def_arch_from = params[:army][:stats][:def_arch_from]
		self.def_arch_to = params[:army][:stats][:def_arch_to]
		self.speed = params[:army][:stats][:speed]
		self.unit_type = params[:army][:stats][:type]
		self.columns = params[:army][:column]
		self.rows = params[:army][:row]
		self.x_pos = params[:army][:x]
		self.y_pos = params[:army][:y]
		self.fight_id = params[:fight_id]
		self.direction = params[:direction]
	end

	def create_targets(params)
		if params[:army][:targets]
			params[:army][:targets].each do |t|
				target = Target.new(
					:army_id => self.id, 
					:x => t['x'], 
					:y => t['y'],
					:stay_time => t['time'])
				target.save!
			end
		end
	end

end

app/models/fight.rb
class Fight < ActiveRecord::Base
	belongs_to :user
	has_many :armies, :dependent => :destroy
end

app/models/target.rb
class Target < ActiveRecord::Base
	belongs_to :army
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :fights, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/armies_controller.rb
class ArmiesController < ApplicationController
  before_action :set_army, only: [:show, :edit, :update, :destroy]

  def index
    @armies = Army.all
  end

  def show
  end

  def new
    render :json => { :status => :ok, :message => params }
  end

  def edit
  end

  def create
    @army = Army.new
    @army.create_army(params)
    @army.save
    @army.create_targets(params)
    fight = @army.fight
    fight.touch
    render :json => { :status => :ok, :message => params }
  end

  def update
    respond_to do |format|
      if @army.update(army_params)
        format.html { redirect_to @army, notice: 'Army was successfully updated.' }
        format.json { render :show, status: :ok, location: @army }
      else
        format.html { render :edit }
        format.json { render json: @army.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @army.destroy
    respond_to do |format|
      format.html { redirect_to armies_url, notice: 'Army was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_army
      @army = Army.find(params[:id])
    end

    def army_params
      params.require(:army).permit(:fight_id, :unit_name, :speed, :hp_from, :hp_to, :dmg_from, :dmg_to, :def_inf_from, :def_inf_to, :def_hors_from, :def_hors_to, :def_arch_from, :def_arch_to, :unit_type, :columns, :rows, :x_pos, :y_pos)
    end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authenticate_user!, :except => [:index, :new, :edit, :destroy]

  def index
    @fights = Fight.where(:user_id => current_user.id).order(updated_at: :desc).paginate(:page => params[:page], :per_page => 30)
  end

  def all_fights
    @fights = Fight.all.order(updated_at: :desc).paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @fight = Fight.find(params[:id])
    targets = []
    @fight.armies.each do |a|
      a.targets.each do |t|
        targets.push([t.id, t.army_id, t.x, t.y, t.stay_time])
      end
    end
    render :json => { :status => :ok, :fight => @fight.armies.as_json, :targets => targets.as_json, :name => @fight.name }
  end

  def new
    @fight = Fight.new
  end

  def play
    @fight = Fight.find_by_id(params[:id])
    if !@fight
      redirect_to root_path
    end
  end

  def watched_fight
    ActiveRecord::Base.record_timestamps = false
    begin
      @fight = Fight.find(params[:id])
      @fight.watched = @fight.watched.to_i + 1
      @fight.save
    ensure
      ActiveRecord::Base.record_timestamps = true
    end
    render :json => { :status => :ok, :fight => @fight.id }
  end

  def edit
    if (@fight.user_id != current_user.id) && (current_user.nickname != 'mansim')
      redirect_to root_path
    end
  end

  def create
    @fight = Fight.create!(:name => params[:fight_name], :user_id => current_user.id)
    render :json => { :status => :ok, :fight => @fight.id }
  end

  def update
    @fight.name = params[:fight_name]
    @fight.save!
    render :json => { :status => :ok, :fight => @fight.id }
  end

  def destroy_armies
    fight = Fight.find(params[:fight_id])
    fight.armies.destroy_all
    render :json => { :status => :ok, :message => 'destroyed' }
  end

  def destroy
    @fight.destroy
    respond_to do |format|
      format.html { redirect_to all_fights_url }
      format.json { head :no_content }
    end
  end

  private
    def set_fight
      @fight = Fight.find(params[:id])
    end

    def fight_params
      params.require(:fight).permit(:name, :user_id, :watched)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:index, :tutorial, :events]

  def index
  end

  def armyfight
  end

  def tutorial
  end

  def events
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout 'application'

  private

  def sign_up_params
    params.require(:user).permit(:name, :surname, :role, :nickname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :surname, :role, :nickname, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armies_helper.rb
module ArmiesHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/armies/_form.html.erb
<%= form_for(@army) do |f| %>
  <% if @army.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@army.errors.count, "error") %> prohibited this army from being saved:</h2>

      <ul>
      <% @army.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fight_id %><br>
    <%= f.number_field :fight_id %>
  </div>
  <div class="field">
    <%= f.label :unit_name %><br>
    <%= f.text_field :unit_name %>
  </div>
  <div class="field">
    <%= f.label :hp_from %><br>
    <%= f.number_field :hp_from %>
  </div>
  <div class="field">
    <%= f.label :hp_to %><br>
    <%= f.number_field :hp_to %>
  </div>
  <div class="field">
    <%= f.label :dmg_from %><br>
    <%= f.number_field :dmg_from %>
  </div>
  <div class="field">
    <%= f.label :dmg_to %><br>
    <%= f.number_field :dmg_to %>
  </div>
  <div class="field">
    <%= f.label :def_inf_from %><br>
    <%= f.number_field :def_inf_from %>
  </div>
  <div class="field">
    <%= f.label :def_inf_to %><br>
    <%= f.number_field :def_inf_to %>
  </div>
  <div class="field">
    <%= f.label :def_hors_from %><br>
    <%= f.number_field :def_hors_from %>
  </div>
  <div class="field">
    <%= f.label :def_hors_to %><br>
    <%= f.number_field :def_hors_to %>
  </div>
  <div class="field">
    <%= f.label :def_arch_from %><br>
    <%= f.number_field :def_arch_from %>
  </div>
  <div class="field">
    <%= f.label :def_arch_to %><br>
    <%= f.number_field :def_arch_to %>
  </div>
  <div class="field">
    <%= f.label :unit_type %><br>
    <%= f.text_field :unit_type %>
  </div>
  <div class="field">
    <%= f.label :columns %><br>
    <%= f.number_field :columns %>
  </div>
  <div class="field">
    <%= f.label :rows %><br>
    <%= f.number_field :rows %>
  </div>
  <div class="field">
    <%= f.label :x_pos %><br>
    <%= f.number_field :x_pos %>
  </div>
  <div class="field">
    <%= f.label :y_pos %><br>
    <%= f.number_field :y_pos %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/armies/edit.html.erb
<h1>Editing Army</h1>

<%= render 'form' %>

<%= link_to 'Show', @army %> |
<%= link_to 'Back', armies_path %>

app/views/armies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Armies</h1>

<table>
  <thead>
    <tr>
      <th>Fight</th>
      <th>Unit name</th>
      <th>Hp from</th>
      <th>Hp to</th>
      <th>Dmg from</th>
      <th>Dmg to</th>
      <th>Def inf from</th>
      <th>Def inf to</th>
      <th>Def hors from</th>
      <th>Def hors to</th>
      <th>Def arch from</th>
      <th>Def arch to</th>
      <th>Unit type</th>
      <th>Columns</th>
      <th>Rows</th>
      <th>X pos</th>
      <th>Y pos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @armies.each do |army| %>
      <tr>
        <td><%= army.fight_id %></td>
        <td><%= army.unit_name %></td>
        <td><%= army.hp_from %></td>
        <td><%= army.hp_to %></td>
        <td><%= army.dmg_from %></td>
        <td><%= army.dmg_to %></td>
        <td><%= army.def_inf_from %></td>
        <td><%= army.def_inf_to %></td>
        <td><%= army.def_hors_from %></td>
        <td><%= army.def_hors_to %></td>
        <td><%= army.def_arch_from %></td>
        <td><%= army.def_arch_to %></td>
        <td><%= army.unit_type %></td>
        <td><%= army.columns %></td>
        <td><%= army.rows %></td>
        <td><%= army.x_pos %></td>
        <td><%= army.y_pos %></td>
        <td><%= link_to 'Show', army %></td>
        <td><%= link_to 'Edit', edit_army_path(army) %></td>
        <td><%= link_to 'Destroy', army, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Army', new_army_path %>

app/views/armies/new.html.erb
<h1>New Army</h1>

<%= render 'form' %>

<%= link_to 'Back', armies_path %>

app/views/armies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fight:</strong>
  <%= @army.fight_id %>
</p>

<p>
  <strong>Unit name:</strong>
  <%= @army.unit_name %>
</p>

<p>
  <strong>Hp from:</strong>
  <%= @army.hp_from %>
</p>

<p>
  <strong>Hp to:</strong>
  <%= @army.hp_to %>
</p>

<p>
  <strong>Dmg from:</strong>
  <%= @army.dmg_from %>
</p>

<p>
  <strong>Dmg to:</strong>
  <%= @army.dmg_to %>
</p>

<p>
  <strong>Def inf from:</strong>
  <%= @army.def_inf_from %>
</p>

<p>
  <strong>Def inf to:</strong>
  <%= @army.def_inf_to %>
</p>

<p>
  <strong>Def hors from:</strong>
  <%= @army.def_hors_from %>
</p>

<p>
  <strong>Def hors to:</strong>
  <%= @army.def_hors_to %>
</p>

<p>
  <strong>Def arch from:</strong>
  <%= @army.def_arch_from %>
</p>

<p>
  <strong>Def arch to:</strong>
  <%= @army.def_arch_to %>
</p>

<p>
  <strong>Unit type:</strong>
  <%= @army.unit_type %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @army.columns %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @army.rows %>
</p>

<p>
  <strong>X pos:</strong>
  <%= @army.x_pos %>
</p>

<p>
  <strong>Y pos:</strong>
  <%= @army.y_pos %>
</p>

<%= link_to 'Edit', edit_army_path(@army) %> |
<%= link_to 'Back', armies_path %>

app/views/fights/_canvas_elements.html.erb
<div class="col-md-7" style='left: -15px;'>
    <canvas id="background" class="background" style="border: 1px solid #2199e8; position:absolute" >
      Your browser does not support canvas element. Please use Chrome / Mozilla or newer Internet Explorer browser.
  </canvas>
  <canvas id="unit_deaths" class="unit_deaths" style="border: 1px solid #2199e8; position:absolute" >
      Your browser does not support canvas element. Please use Chrome / Mozilla or newer Internet Explorer browser.
  </canvas>
  <canvas id="game" class="game_canvas" style="border: 1px solid #2199e8; position:absolute">
      Your browser does not support canvas element. Please use Chrome / Mozilla or newer Internet Explorer browser.
  </canvas>

</div>

app/views/fights/_form.html.erb
<%= render 'layouts/navigation' %>
<%= render 'fights/images' %>
<%= render 'fights/canvas_elements' %>
<%= render 'fights/units_stats' %>
<%= render 'fights/units_targets' %>
<%= render 'fights/units_formations' %>

<div class="col-md-offset-7 col-md-5">
  <div class="form-group row">
      <div class="col-md-5 columns">
          <input type="text" data-ng-model='fight_name' id="fight_name" placeholder="Input fight name" data-ng-change = 'saved=false' class='form-control'>
      </div>
      <div class="col-md-3 columns">
          <button class='btn btn-primary' data-ng-show=!saved data-ng-click="save_fight()">Save</button>
          <button class='btn btn-success' data-ng-show=saved data-ng-click="save_fight()">Saved</button>
      </div>
      <div class="col-md-4 columns">
          <button class='btn btn-success' data-ng-click="army_view = 0" data-ng-show="edit_army_view(1)">Hide Army stats</button>
          <button class='btn btn-success' data-ng-click="army_view = 0" data-ng-show="edit_army_view(2)">Hide Army stats</button>
          <button class='btn btn-success' data-ng-click="army_view = 0" data-ng-show="edit_army_view(3)">Hide Army stats</button>
          <button class='btn btn-success' data-ng-click="army_view = 1" data-ng-show="edit_army_view(0)">Show Army stats</button>
      </div>
  </div>

  <div class="form-group row">
      <div class="col-md-5 columns">
          <label class="form-control-label"> Attackers count: </label>
      </div>
      <div class="col-md-2 columns">
          <div data-ng-bind="countAlly"></div>
      </div>
      <div class="col-md-5 columns">
          <button class='btn btn-primary' data-ng-click="add_army('ally')" style='width:170px;'>Add attacker army</button>
      </div>
  </div>

  <div class="form-group row">
      <div class="col-md-5 columns">
          <label class="form-control-label"> Defenders count: </label>
      </div>
      <div class="col-md-2 columns">
          <div data-ng-bind="countEnemy"></div>
      </div>
      <div class="col-md-5 columns">
          <button class='btn btn-primary' data-ng-click="add_army('enemy')" style='width:170px;'>Add defender army</button>
      </div>
  </div>

  <div class="form-group row">
      <div class="col-md-4 columns">
          <label class="form-control-label"> Army type </label>
      </div>
      <div class="col-md-2 columns">
          <label class="form-control-label"> Rows </label>
      </div>
      <div class="col-md-2 columns">
          <label class="form-control-label"> Columns </label>
      </div>
      <div class="col-md-4 columns">
      </div>
  </div>

  <div data-ng-repeat="(key, value) in formations.ally">
    <div class="form-group row">
        <div class="col-md-4 columns">
            <select data-ng-model="value.unit" data-ng-change="change_stats(key, 'ally')" class="form-control" style="background-color:#ec5840; color:white;">
                <option value="spear">Spearman</option>
                <option value="sword">Swordsman</option>
                <option value="axe">Axemen</option>
                <option value="bow">Bowman</option>
                <option value="light">Light cavalry</option>
                <option value="mounted">Mounted archer</option>
                <option value="heavy">Heavy cavalry</option>
            </select>
        </div>
        <div class="col-md-2 columns">
            <input type="text" data-ng-model="value.row" data-ng-change="change_stats(key, 'ally')" class="form-control">
        </div>
        <div class="col-md-2 columns">
            <input type="text" data-ng-model="value.column" data-ng-change="change_stats(key, 'ally')" class="form-control">
        </div>
        <div class="col-md-4 columns">
            <button data-ng-class="find_class(key, 'ally')" data-ng-click="change_unit_stats('ally', key)">Select</button>
            <button class='btn btn-danger' data-ng-click="remove(key, 'ally')">X</button>
        </div>
    </div>
  </div>


  <div data-ng-repeat="(key, value) in formations.enemy">
    <div class="form-group row">
        <div class="col-md-4 columns">
            <select data-ng-model="value.unit" data-ng-change="change_stats(key, 'enemy')" class="form-control" style="background-color:#2199e8; color:white;">
                <option value="spear">Spearman</option>
                <option value="sword">Swordsman</option>
                <option value="axe">Axemen</option>
                <option value="bow">Bowman</option>
                <option value="light">Light cavalry</option>
                <option value="mounted">Mounted archer</option>
                <option value="heavy">Heavy cavalry</option>
            </select>
        </div>
        <div class="col-md-2 columns">
            <input type="text" data-ng-model="value.row" data-ng-change="change_stats(key, 'enemy')" class="form-control">
        </div>
        <div class="col-md-2 columns">
            <input type="text" data-ng-model="value.column" data-ng-change="change_stats(key, 'enemy')" class="form-control">
        </div>
        <div class="col-md-4 columns">
            <button data-ng-class="find_class(key, 'enemy')" data-ng-click="change_unit_stats('enemy', key)">Select</button>
            <button class='btn btn-danger' data-ng-click="remove(key, 'enemy')">X</button>
        </div>
    </div>
  </div>
</div>

app/views/fights/_play_buttons.html.erb
<div style='width: 110px; float:right;'>
    <br>

    <span><a href="/" class="btn btn-default">Home</a></span><br><br>
    <button class="btn btn-primary armywatch" data-ng-show='!attacking' data-ng-click="start_attack()">Attack</button>
    <button class="btn btn-primary armywatch" data-ng-show='attacking' data-ng-click="start_attack()">Stop</button>

    <% if current_user && current_user.nickname == 'mansim' %>
        <button class="btn btn-primary armywatch" data-ng-click="log()">LOG</button>
    <% end %>

    <br><br>
    Units count:<br>
    
    <div class="armywatch text-center" data-ng-bind="countAlly" style="background-color: #f04124; color:white"></div>
    <div class="armywatch text-center" data-ng-bind="countEnemy" style="background-color: rgb(33, 153, 232); color:white"></div>
    <br>
    Quality:<br>
    <a style='color:#7E7E7E' data-ng-click="low_graphics()" data-ng-disabled="changing_image"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i> Low</a><br>
    <a style='color:#3F3F3F' data-ng-click="normal_graphics()" data-ng-disabled="changing_image"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i> Medium</a><br>
    <a style='color:black' data-ng-click="best_graphics()" data-ng-disabled="changing_image"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i> Best</a><br>
   
	Zoom:<br>
    <a data-ng-click="plus_size()"><i class="fa fa-search-plus fa-3x" ></i></a>
    <a data-ng-click="minus_size()"><i class="fa fa-search-minus fa-3x"></i></a>

    <br>
    Speed:<br>
    <div class='btn-group'>
        <button ng-class="change_speed_button(150)" data-ng-click="change_speed(150)"></button>
        <button ng-class="change_speed_button(80)" data-ng-click="change_speed(80)"></button>
        <button ng-class="change_speed_button(40)" data-ng-click="change_speed(40)"></button>
        <button ng-class="change_speed_button(1)" data-ng-click="change_speed(1)"></button>
    </div>
</div>

app/views/fights/_units_formations.html.erb
<div class="col-md-offset-3 col-md-4" style='left: -8px; position:absolute; background-color: rgba(33, 153, 132, 0.8); color:white;' 
data-ng-show="edit_army_view(3)">

    <button class="btn btn-primary" data-ng-click='army_view = 1'>Stats page</button>
    <button class="btn btn-primary" data-ng-click='army_view = 2'>Targets page</button>
    <button class="btn btn-primary" data-ng-click='army_view = 3'>Formations page</button>



    <div class="row" style='padding-top:10px;'>
        <div class="col-md-6 columns">
            <button class="btn btn-success" data-ng-click='center_army()'>Center this army</button>
            <button class="btn btn-success" data-ng-click='deselect_army()' style='display:inline; float:right;'>Deselect this army</button>
        </div>
        <div class="col-md-6 columns">
            This feature is not yet implemented
        </div>
    </div>


    <br>

</div>

app/views/fights/all_fights.html.erb
<%= render 'layouts/navigation' %>
<div class='col-md-offset-2 col-md-8'>
<%= will_paginate @fights, renderer: BootstrapPagination::Rails %>
<h1 class='text-center'>All Fights</h1>
<%= link_to 'New Fight', new_fight_path, :class => 'btn btn-success' %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>User</th>
      <th>Created</th>
      <th>Updated</th>
      <th>Watched</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |fight| %>
      <tr>
        <td><%= fight.id %></td>
        <td><%= fight.name.truncate(30) %></td>
        <td><%= fight.user.nickname %></td>
        <td><%= fight.created_at.strftime("%Y-%m-%d %Hh") %></td>
        <td><%= fight.updated_at.strftime("%Y-%m-%d %Hh") %></td>
        <td><%= fight.watched %></td>
        <td><a href="/play/<%= fight.id %>"  class='btn btn-primary'>Watch</a></td>
        <% if current_user && current_user.nickname == 'mansim' %>
          <td><%= link_to 'Edit', edit_fight_path(fight), :class => 'btn btn-primary' %></td>
          <td><%= link_to 'Destroy', fight, method: :delete, :class => 'btn btn-danger' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

</div>

app/views/fights/edit.html.erb
<div data-ng-app="app" data-ng-controller="game" data-ng-init = "fight_editing(<%= @fight.id %>)">
<%= render 'form' %>
</div>

app/views/fights/index.html.erb
<%= render 'layouts/navigation' %>
<div class="container">
<div class='col-md-offset-2 col-md-8'>
<h1 class='text-center'>All Fights</h1>
<%= will_paginate @fights, renderer: BootstrapPagination::Rails %>
<%= link_to 'New Fight', new_fight_path, :class => 'btn btn-success' %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fights.each do |fight| %>
      <tr>
        <td><%= fight.id %></td>
        <td><%= fight.name.truncate(30) %></td>
        <td><%= fight.created_at.strftime("%Y %m %d %H:%M:%S") %></td>
        <td><%= fight.updated_at.strftime("%Y %m %d %H:%M:%S") %></td>
        <td><a href="/play/<%= fight.id %>" class='btn btn-primary'>Watch</a></td>
        <td><%= link_to 'Edit', edit_fight_path(fight), :class => 'btn btn-primary' %></td>
        <td><%= link_to 'Destroy', fight, method: :delete, :class => 'btn btn-danger' %></td>
      </tr>
    <% end %>
 
  </tbody>
</table>
<br>


</div>
</div>

app/views/fights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fight.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @fight.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @fight.user_id %>
</p>

<p>
  <strong>Password:</strong>
  <%= @fight.password %>
</p>

<%= link_to 'Edit', edit_fight_path(@fight) %> |
<%= link_to 'Back', fights_path %>

app/views/home/index.html.erb
<%= render 'layouts/navigation' %>
<div class="container">
<div class="col-md-3 col-md-offset-4">
<h3><%= link_to "Watch fights without registration", all_fights_path, :class => "btn btn-primary" %></h3>
</div>
<div class="col-md-9">
		<%= image_tag('af.png', :class => 'thumbnail', :size => "1000x600") %>
		<p>Create your own Army formations, Unit stats, Units count and Army placement</p>

</div><br><br>

</div>

app/views/layouts/_navigation.html.erb
<div class="container">
<nav class="navbar navbar-default">
	<div class="container-fluid">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	      <span class="sr-only">Toggle navigation</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="/">ArmyFight</a>
	  </div>
	  <div id="navbar" class="navbar-collapse collapse">
	    <ul class="nav navbar-nav">
	      <li class="active"><%= link_to('Home', root_path) %></li>
	      <li><%= link_to('About', tutorial_path) %></li>
	      <li><%= link_to('Watch fights', all_fights_path) %></li>
	      <% if user_signed_in? %>
	      <li class="dropdown">
	        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User page <span class="caret"></span></a>
	        <ul class="dropdown-menu">
	            <li><%= link_to('Your fights', fights_path) %></li>
	            <li><%= link_to 'New fight', new_fight_path %></li>
	        </ul>
	      </li>
	      <% end %>
	    </ul>
	    <ul class="nav navbar-nav navbar-right">
	        <% if user_signed_in? %>
	        	<li class="active"><%= link_to "Sign Out #{current_user.nickname}", destroy_user_session_path, :method => :delete %></li>
	        <% else %>
	        	<li class="active"><%= link_to "Log in", new_session_path(:user) %></li>
	        	<li><%= link_to "Sign up", new_registration_path(:user) %></li>
	        <% end %>
	    </ul>
	  </div>
	</div>
</nav>

</div>